name: /stanley/WangLab/envs/stardist
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2023.12.12
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.4
  - openssl=3.0.13
  - pip=23.3.1
  - python=3.9.18
  - readline=8.2
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tk=8.6.12
  - tzdata=2023d
  - wheel=0.41.2
  - xz=5.4.5
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - astunparse==1.6.3
      - cachetools==5.3.2
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - contourpy==1.2.0
      - csbdeep==0.7.4
      - cycler==0.12.1
      - flatbuffers==23.5.26
      - fonttools==4.49.0
      - gast==0.5.4
      - google-auth==2.28.0
      - google-auth-oauthlib==1.2.0
      - google-pasta==0.2.0
      - grpcio==1.60.1
      - h5py==3.10.0
      - idna==3.6
      - imagecodecs==2024.9.22
      - imageio==2.34.0
      - importlib-metadata==7.0.1
      - importlib-resources==6.1.1
      - keras==2.15.0
      - kiwisolver==1.4.5
      - lazy-loader==0.3
      - libclang==16.0.6
      - llvmlite==0.42.0
      - markdown==3.5.2
      - markupsafe==2.1.5
      - matplotlib==3.8.3
      - ml-dtypes==0.2.0
      - networkx==3.2.1
      - numba==0.59.0
      - numpy==1.26.4
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - packaging==23.2
      - pillow==10.2.0
      - protobuf==4.25.3
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - scikit-image==0.22.0
      - scipy==1.12.0
      - six==1.16.0
      - stardist==0.8.5
      - tensorboard==2.15.2
      - tensorboard-data-server==0.7.2
      - tensorflow==2.15.0.post1
      - tensorflow-estimator==2.15.0
      - tensorflow-io-gcs-filesystem==0.36.0
      - termcolor==2.4.0
      - tifffile==2024.2.12
      - tqdm==4.66.2
      - typing-extensions==4.9.0
      - urllib3==2.2.1
      - werkzeug==3.0.1
      - wrapt==1.14.1
      - zipp==3.17.0
prefix: /stanley/WangLab/envs/stardist
